language: cpp
sudo: false

common_sources: &all_sources
  - ubuntu-toolchain-r-test
  - llvm-toolchain-trusty

matrix:
  include:

    # 1/ OSX Builds
    - env: COMPILER='clang++' COMPILER_CC='clang' LLVM_CONFIG='llvm-config'  COVERAGE='No'
      os: osx
      osx_image: xcode9.3
      compiler: clang
      
    # 2/ Linux Clang Builds
    - os: linux
      compiler: clang
      addons:
          apt:
              sources: *all_sources
              packages: ['clang-7', 'libstdc++-6-dev', 'llvm-7-dev', 'libclang-7-dev', 'zlib1g-dev']
      env: COMPILER='clang++-7' COMPILER_CC='clang-7' LLVM_CONFIG='/usr/bin/llvm-config-7'  COVERAGE='No'

    # 3/ Linux GCC Builds
    - os: linux
      compiler: gcc
      addons: &gcc8
        apt:
          sources: *all_sources
          packages: ['g++-8', 'clang-7', 'libstdc++-6-dev', 'llvm-7-dev', 'libclang-7-dev', 'zlib1g-dev']
      env: COMPILER='g++-8' COMPILER_CC='gcc-8' LLVM_CONFIG='/usr/bin/llvm-config-7' COVERAGE='No'

    # 3/ Linux Clang Coverage Builds
    - os: linux
      compiler: gcc
      addons: &gcc8
        apt:
          sources: *all_sources
          packages: ['g++-7', 'clang-7', 'libstdc++-6-dev', 'llvm-7-dev', 'libclang-7-dev', 'zlib1g-dev', 'lcov']
      env: COMPILER='g++-7' COMPILER_CC='gcc-7' LLVM_CONFIG='/usr/bin/llvm-config-7' COVERAGE='Yes'
      
install:
  - ${TRAVIS_BUILD_DIR}/scripts/travis_install.sh
    
before_script:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        export PATH=${TRAVIS_BUILD_DIR}/clang/current/bin:$PATH
    fi
  - export CXX=${COMPILER}
  - export CC=${COMPILER_CC}
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build
  - cd build
  - cmake -DINSIGHTS_LLVM_CONFIG=${LLVM_CONFIG} -DINSIGHTS_COVERAGE=${COVERAGE}  ..

script:
  - make -j 2
  - ${TRAVIS_BUILD_DIR}/scripts/travis_tests.sh

after_success:
  - ${TRAVIS_BUILD_DIR}/scripts/travis_coverage.sh

