version: '{build}'
image: Visual Studio 2019
environment:
  auth_token:
    secure: 2CkXU3zp0qx8s0lktLoLk+o9XO1/wGUdH5+HYxIzSwc7XU4rP8kphX1RtFycnWfa

install:
  - cmd: if not exist C:\llvm-bin\downloaded ( 
            mkdir C:\llvm-bin &&
            cd C:\llvm-bin &&
            (powershell Start-FileDownload "https://github.com/andreasfertig/cppinsights-compiler-binaries/releases/download/10.0.0/llvm+clang-10.0.0-win64-msvc-release.tar.xz" -FileName llvm.tar.xz) &&
            7z x C:\llvm-bin\llvm.tar.xz &&
            7z x C:\llvm-bin\llvm.tar &&
            del llvm.tar &&
            echo "downloaded" > downloaded )
  - cmd: set PATH=%PATH%;C:\llvm-bin\llvm+clang-10.0.0-win64-msvc-release\bin
  - cmd: echo PATH %PATH%
  - cmd: md c:\ciuploadtool
  - cmd: cd c:\ciuploadtool
  - cmd: curl -fsSL https://github.com/d1vanov/ciuploadtool/releases/download/continuous-master/ciuploadtool_windows_x86.zip -o ciuploadtool_windows_x86.zip
  - cmd: 7z x ciuploadtool_windows_x86.zip
  - cmd: curl -Ls -o "LLVM_VS2017.zip" "https://github.com/zufuliu/llvm-utils/releases/download/v19.05/LLVM_VS2017.zip"
  - cmd: 7z x -y "LLVM_VS2017.zip" >NUL
  - cmd: CALL "LLVM_VS2017\install.bat" 1
    

cache:
  - C:\llvm-bin -> appveyor.yml

build_script:
  - cmd: mkdir "%APPVEYOR_BUILD_FOLDER%/build"
  - cmd: cd "%APPVEYOR_BUILD_FOLDER%/build"
  - cmd: clang++ --version
  - cmd: cmake -G "Visual Studio 16 2019" -A x64 -T LLVM_v142 -DINSIGHTS_STATIC=Yes -DINSIGHTS_LLVM_CONFIG=C:\llvm-bin\llvm+clang-10.0.0-win64-msvc-release\bin\llvm-config ..

  - cmd: cmake --build . --config Release --target insights
  - cmd: cd Release
  - cmd: dir
  - cmd: 7z a insights-windows-64bit.zip insights.exe

on_finish:
  - cmd: if "%APPVEYOR_PULL_REQUEST_NUMBER%" == "" ( if "%APPVEYOR_REPO_BRANCH%" == "master" ( c:\ciuploadtool\ciuploadtool.exe insights-windows-64bit.zip ) )

branches:
  except:
    - /^(?i:continuous)$/
