version: '{build}'
image: Visual Studio 2017

install:
  - cmd: if not exist C:\llvm-bin\downloaded ( 
            mkdir C:\llvm-bin &&
            cd C:\llvm-bin &&
            (powershell Start-FileDownload "https://ziglang.org/deps/llvm+clang-8.0.0-win64-msvc-release.tar.xz" -FileName llvm.tar.xz) &&
            7z x C:\llvm-bin\llvm.tar.xz &&
            7z x C:\llvm-bin\llvm.tar &&
            echo "downloaded" > downloaded )
  - cmd: set PATH=%PATH%;C:\llvm-bin\llvm+clang-8.0.0-win64-msvc-release\bin
  - cmd: echo PATH %PATH%

cache:
  - C:\llvm-bin -> appveyor.yml

build_script:
  - cmd: mkdir "%APPVEYOR_BUILD_FOLDER%/build"
  - cmd: cd "%APPVEYOR_BUILD_FOLDER%/build"
  - cmd: clang++ --version
  - cmd: cmake -G "Visual Studio 15 2017 Win64" -T LLVM -DINSIGHTS_LLVM_CONFIG=C:\llvm-bin\llvm+clang-8.0.0-win64-msvc-release\bin\llvm-config ..

  - cmd: cmake --build . --config Release --target insights
  - cmd: cd Release
  - cmd: dir
  - cmd: 7z a insights-windows-64bit.zip insights.exe
